name: matrix-configuration
on: workflow_dispatch
  
jobs:
  deploy-on-ubuntu:
    runs-on: [self-hosted,'runner1']
    
    steps:
      - name: hello-world-on-self-hosted-runner
        run: echo "hello welcome"