name: deploy-docker-image
on: 
  push:
    branches: 
      - main

jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Pull, tag and push Docker image
        run: |
          docker pull hello-world
          # Tag the pulled image with your Docker Hub repo (add a tag, e.g. latest)
          docker tag hello-world docker.io/${{ vars.DOCKER_USERNAME }}/hello-world:latest
          docker push docker.io/${{ vars.DOCKER_USERNAME }}/hello-world:latest
